dash_board/board/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .dash_apps.finished import map
from .dash_apps.finished import without_vpn
from .dash_apps.finished import without_vpn_mts
from .dash_apps.finished import without_vpn_tele2
from .dash_apps.finished import without_vpn_mgts
from .dash_apps.finished import without_vpn_beeline
from .dash_apps.finished import without_vpn_megafon
from .dash_apps.finished import without_vpn_rostelecom
from .dash_apps.finished import without_vpn_rostelecom_mobile
from .dash_apps.finished import dynamic_graph
from .dash_apps.finished import dynamic_graph_table
# from .dash_apps.finished import asn_data


app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('analytics/', views.analytics, name='analytics'),
    path('file/<str:filename>/', views.download_file, name='download_file'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash_board/dash_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('board.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

dash_board/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetView,
    PasswordChangeDoneView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

dash_board/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    position = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Должность',
    )
    class Meta:
        permissions = (
            ('vpn_performance', 'vpn performance'),
            ('map', 'map'),
            ('interactive_chart', 'interactive chart'),
            ('access_to_blocked_resources', 'access to blocked resources'),
            ('reports_and_documents', 'reports and documents'),
            ('new_func', 'new function'),
            ('archive', 'archive'),
            ('main_page', 'main page'),
            ('analytics', 'analytics'),
        )
    def __str__(self):
        return self.username

dash_board/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'position',
        )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'username', 'email', 'position',)

dash_board/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.mixins import UserPassesTestMixin

from .forms import CustomUserCreationForm


# class SignUp(CreateView):
#     form_class = CustomUserCreationForm
#     success_url = reverse_lazy('board:index')
#     template_name = 'users/signup.html'

class SignUp(UserPassesTestMixin, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('board:index')
    template_name = 'users/signup.html'

    def test_func(self):
        return self.request.user.is_staff

dash_board/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}
  Вы вышли из системы
{% endblock %}
{% block content %}
<header class="u-clearfix u-header u-header" id="sec-175f"><div class="u-clearfix u-sheet u-sheet-1">
        <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
          <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
            <a class="u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-text-shadow u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</g></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-nav u-unstyled u-nav-1">
                              <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'users:login' %}" style="padding: 10px 50px 10px 48px;">Вход</a>
</li>
            </ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2">
                <li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="{% url 'users:login' %}" style="padding: 10px 50px 10px 48px;">Вход</a>
</li>
                </ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div>
  </header>

    <!-- Bootstrap CSS -->
{% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

dash_board/templates/users/login.html
<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
        {% load static %}
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Вход</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/login.css' %}" media="screen">
{#    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>#}
{#    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>#}


{#    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">#}
{#    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">#}
    
{#    {% extends 'base.html' %}#}
{##}
{#{% block title %}#}
{#    Главная#}
{#{% endblock title %}#}
{##}
{#{% block content %}#}



    <meta property="og:title" content="Вход">

  <meta data-intl-tel-input-cdn-path="intlTelInput/"></head>
  <body data-path-to-root="./" class="u-body u-xl-mode" data-lang="ru">
    <section class="u-align-center u-clearfix u-custom-color-16 u-section-1" id="sec-7d5b">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-align-center u-form u-radius-50 u-form-1">

{#      <form class="u-clearfix u-form-custom-backend u-form-spacing-10 u-form-vertical u-inner-form" style="padding: 30px;" method="post"#}

            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
        <form class="u-clearfix u-form-spacing-34 u-form-vertical u-inner-form" style="padding: 36px;" method="post"
                {% if action_url %}
              action="{% url action_url %}"
            {% endif %} >
          {% csrf_token %}
{#          <form action="https://forms.nicepagesrv.com/v2/form/process" class="u-clearfix u-form-spacing-34 u-form-vertical u-inner-form" style="padding: 36px;" source="email" name="form">#}
            <div class="u-form-group u-form-name u-label-none">
              <label for="id_username" class="u-label">Имя пользователя</label>
              <input type="text" placeholder="Введите имя пользователя" id="id_username" name="username" class="u-border-none u-custom-font u-font-montserrat u-input u-input-rectangle u-radius-50 u-text-custom-color-15 u-input-1" required="">
            </div>
            <div class="u-form-email u-form-group u-label-none">
              <label for="id_password" class="u-label">Пароль</label>
              <input type="password" placeholder="Введите пароль" id="id_password" name="password" class="u-border-none u-custom-font u-font-montserrat u-input u-input-rectangle u-radius-50 u-text-custom-color-15 u-input-2" required="">
            </div>

            <div class="u-align-right u-form-group u-form-submit u-label-none">

                <button type="submit" class="u-active-custom-color-3 u-border-none u-btn u-btn-round u-btn-submit u-button-style u-custom-color-2 u-custom-font u-font-montserrat u-hover-custom-color-3 u-radius-50 u-text-active-custom-color-16 u-text-hover-custom-color-16 u-btn-1">
                Войти
            </button>
{#              <a href="#" class="u-active-custom-color-3 u-border-none u-btn u-btn-round u-btn-submit u-button-style u-custom-color-2 u-custom-font u-font-montserrat u-hover-custom-color-3 u-radius-50 u-text-active-custom-color-16 u-text-hover-custom-color-16 u-btn-1">Войти</a>#}
            </div>

          </form>

        </div>
      </div>
    </section>
    
    

  
</body></html>

dash_board/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}
  Пароль изменен
{% endblock %}

{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

dash_board/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}
  Изменение пароля
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
            >
            {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                  Старый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

dash_board/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

dash_board/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
  Новый пароль
{% endblock %}

{% block content %}
    {% if validlink %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
                >
                {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
      </div>
    {% else %}
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
                <div class="card">
                    <div class="card-header">Ошибка</div>
                    <div class="card-body">
                        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
                    </div> <!-- card body -->
                </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
    {% endif %}
{% endblock %}

dash_board/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля прошёл успешно
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

dash_board/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}
  Сброс пароля
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="post"
                {% if action_url %}
                  action="{% url action_url %}"
                {% endif %}
            >
                {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

dash_board/templates/users/signup.html
{% extends "base.html" %}
{% block title %}
  Зарегистрироваться
{% endblock %}
{% block content %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">

              {% if form.errors %}
                  {% for field in form %}
                      {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post"
                {% if action_url %}
                    action="{% url action_url %}"
                {% endif %}
                >
                {% csrf_token %}

              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}